import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "@/shared/styles/globals.css";
import NavbarWrapper from "@/shared/components/navbar/NavbarWrapper";
import ScrollToTop from "@/shared/components/scroll-to-top/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <Suspense fallback={<div className="h-14" />}>
          <NavbarWrapper isAuthenticated={false} />
        </Suspense>
        <ScrollToTop />

        {/* Page content (Home, Profile, Items, etc.) */}
        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}